version: '3.7'
services:
  postgres:
    image: 'postgres:10.0'
    restart: on-failure
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - net
  nginx:
    image: 'nginx:1.15.3-alpine'
    ports:
      - '127.0.0.1:80:80'
    restart: on-failure
    volumes:
      - './:/usr/src/skills:delegated'
      - './hosts:/etc/nginx/conf.d/'
    networks:
      net:
        aliases:
          - skills.test
    depends_on:
      - php-skills
  php-skills:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/skills:delegated'
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=skills"
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  postgres-data: null